#!/bin/bash
set -eEo pipefail

# Generate Hyprland bindings from .desktop files
# This script reads .desktop files and generates bindings.generated.conf

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMELING_DIR="$(dirname "$SCRIPT_DIR")"
DESKTOP_DIR="$FRAMELING_DIR/_local/share/applications"
OUTPUT_FILE="$FRAMELING_DIR/_config/hypr\$/bindings.generated.conf"

# Function to convert hotkey format from .desktop to Hyprland
convert_hotkey() {
    local hotkey="$1"
    # Convert Super+Shift+D to SUPER SHIFT, D
    # First replace + with space, then replace modifiers, then add comma before last part
    local parts=(${hotkey//+/ })
    local last_index=$((${#parts[@]} - 1))
    local key="${parts[$last_index]}"
    unset parts[$last_index]
    local modifiers=""
    for mod in "${parts[@]}"; do
        case $mod in
            Super) modifiers="$modifiers SUPER" ;;
            Shift) modifiers="$modifiers SHIFT" ;;
            Alt) modifiers="$modifiers ALT" ;;
            Ctrl) modifiers="$modifiers CTRL" ;;
        esac
    done
    # Trim leading space and add comma
    modifiers=$(echo "$modifiers" | sed 's/^ *//')
    echo "$modifiers, $key"
}



echo "# Generated bindings from .desktop files" > "$OUTPUT_FILE"
echo "# Do not edit manually - generated by $0" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Track used hotkeys to avoid duplicates
declare -A used_hotkeys
declare -A bindings

# Find all .desktop files and collect bindings
while IFS= read -r -d '' desktop_file; do
    # Extract fields
    name=$(grep '^Name=' "$desktop_file" | cut -d'=' -f2-)
    hotkey=$(grep '^Hotkey=' "$desktop_file" | cut -d'=' -f2-)

    if [[ -z "$hotkey" || -z "$name" ]]; then
        continue
    fi

    # Convert hotkey
    hypr_hotkey=$(convert_hotkey "$hotkey")

    # Check for duplicates
    if [[ ${used_hotkeys[$hypr_hotkey]} ]]; then
        echo "Warning: Duplicate hotkey $hypr_hotkey for $name (already used by ${used_hotkeys[$hypr_hotkey]})" >&2
        continue
    fi
    used_hotkeys[$hypr_hotkey]="$name"
    bindings[$hypr_hotkey]="$name|$desktop_file"

done < <(find "$DESKTOP_DIR" -name "*.desktop" -print0)

# Generate all unbinds first
for hypr_hotkey in "${!bindings[@]}"; do
    echo "unbind = $hypr_hotkey" >> "$OUTPUT_FILE"
done

# Then generate all binds
for hypr_hotkey in "${!bindings[@]}"; do
    IFS='|' read -r name desktop_file <<< "${bindings[$hypr_hotkey]}"
    echo "bindd = $hypr_hotkey, $name, exec, webapp-launcher \"$desktop_file\"" >> "$OUTPUT_FILE"
done

echo "Generated bindings in $OUTPUT_FILE"